In [1]:
import pandas as pd

In [3]:
keywords_20 = pd.read_csv('key_words_top20.csv')

In [6]:
list(keywords_20['Keywords'])

['trump',
 'clinton',
 'game',
 'police',
 'say',
 'comment',
 'school',
 'woman',
 'yard',
 'student',
 'election',
 'officer',
 'percent',
 'republican',
 'cub',
 'company',
 'hurricane',
 'child',
 'city',
 'voter']

In [9]:
list(keywords_20['Frequency'])

[994,
 453,
 432,
 396,
 274,
 260,
 249,
 236,
 218,
 208,
 206,
 198,
 167,
 163,
 160,
 157,
 157,
 157,
 150,
 145]

In [10]:
keywords_top20_08 = pd.read_csv('key_words_top20_08.csv')

In [12]:
list(keywords_top20_08['Keywords'])

['trump',
 'police',
 'comment',
 'clinton',
 'school',
 'say',
 'game',
 'student',
 'officer',
 'season',
 'woman',
 'child',
 'percent',
 'rio',
 'city',
 'company',
 'olympic',
 'campaign',
 'county',
 'film']

In [13]:
keywords_top20_08

    Keywords  Frequency
0      trump        687
1     police        388
2    comment        329
3    clinton        328
4     school        263
5        say        254
6       game        246
7    student        200
8    officer        178
9     season        153
10     woman        150
11     child        148
12   percent        135
13       rio        129
14      city        129
15   company        116
16   olympic        116
17  campaign        113
18    county        113
19      film        113

In [14]:
list(keywords_top20_08['Frequency'])

[687,
 388,
 329,
 328,
 263,
 254,
 246,
 200,
 178,
 153,
 150,
 148,
 135,
 129,
 129,
 116,
 116,
 113,
 113,
 113]

In [15]:
keywords_top20_09 = pd.read_csv('key_words_top20_09.csv')

In [16]:
list(keywords_top20_09['Keywords'])

['trump',
 'police',
 'clinton',
 'comment',
 'game',
 'school',
 'say',
 'student',
 'officer',
 'child',
 'percent',
 'bank',
 'woman',
 'yard',
 'season',
 'film',
 'charlotte',
 'city',
 'scott',
 'debate']

In [2]:
mediatopics = pd.read_csv('top30media_freq.csv')

In [7]:
mediatopics.drop(['unknown', 'date', 'country', 'website', 'title'], axis=1, inplace=True)

In [11]:
mediatopics

                media     id
0   Houston Chronicle    133
1            Newsweek    206
2      New York Times    242
3                VICE    402
4      Breitbart News    546
5            Politico    739
6         Daily Beast    750
7        The Atlantic   1093
8     Washington Post   1556
9      Slate Magazine   1916
10            Reuters   2313
11             Quartz   2627
12                CNN   2783
13      New York Post   2794
14               TIME   3795
15          USA TODAY   4338
16                NPR   4694
17    Huffington Post   5190
18           ABC News   5745
19  Los Angeles Times   6607
20           CBS News   6752
21           NBC News   8271
22           Fox News  11641

In [13]:
list(mediatopics['media'])[::-1]

['Fox News',
 'NBC News',
 'CBS News',
 'Los Angeles Times',
 'ABC News',
 'Huffington Post',
 'NPR',
 'USA TODAY',
 'TIME',
 'New York Post',
 'CNN',
 'Quartz',
 'Reuters',
 'Slate Magazine',
 'Washington Post',
 'The Atlantic',
 'Daily Beast',
 'Politico',
 'Breitbart News',
 'VICE',
 'New York Times',
 'Newsweek',
 'Houston Chronicle']

In [14]:
list(mediatopics['id'])[::-1]

[11641,
 8271,
 6752,
 6607,
 5745,
 5190,
 4694,
 4338,
 3795,
 2794,
 2783,
 2627,
 2313,
 1916,
 1556,
 1093,
 750,
 739,
 546,
 402,
 242,
 206,
 133]

In [15]:
mediatrump1610 = pd.read_csv('trump_media_top30_1610.csv')

In [18]:
list(mediatrump1610['media'])

['ABC News',
 'CBS News',
 'CNN',
 'Fox News',
 'Huffington Post',
 'Los Angeles Times',
 'NBC News',
 'Politico',
 'Slate Magazine',
 'The Atlantic',
 'USA TODAY',
 'Washington Post']

In [19]:
list(mediatrump1610['pos'])

[0.3888888888888889,
 0.1176470588235294,
 0.21052631578947367,
 0.21052631578947367,
 0.45,
 0.2972972972972973,
 0.3414634146341464,
 0.3225806451612903,
 0.2222222222222222,
 0.07692307692307693,
 0.07142857142857142,
 0.3404255319148936]

In [20]:
list(mediatrump1610['neg'])

[0.3055555555555556,
 0.5882352941176471,
 0.3157894736842105,
 0.5789473684210527,
 0.25,
 0.16216216216216214,
 0.2926829268292683,
 0.0967741935483871,
 0.4444444444444444,
 0.2307692307692308,
 0.14285714285714285,
 0.1276595744680851]

In [21]:
list(mediatrump1610['neu'])

[0.3055555555555556,
 0.2941176470588235,
 0.4736842105263158,
 0.21052631578947367,
 0.30000000000000004,
 0.5405405405405405,
 0.3658536585365853,
 0.5806451612903226,
 0.33333333333333337,
 0.6923076923076923,
 0.7857142857142858,
 0.5319148936170213]

In [22]:
fox_daily = pd.read_csv('Fox_10_daily.csv')

In [23]:
fox_daily

,Unnamed: 0,Unnamed: 0.1,id,unknown,date,country,media,website,title,year,month,day,txt,polarity,normalized_polarity
0,44,309985,14752920,420,16-10-07,US,Fox News,http://fox13now.com/2016/10/07/congressman-jas...,Congressman Jason Chaffetz withdraws his endor...,16,10,7,"Chaffetz , a Republican representing Utah 's...",0.692308,0.422175
1,81,311192,14776151,426,16-10-09,US,Fox News,http://fox6now.com/2016/10/09/president-obama-...,"President Obama calls Trump's lewd comments ""d...",16,10,9,CHICAGO -- President Barack Obama condemned ...,0.555556,0.285423
2,87,311353,14778721,417,16-10-09,US,Fox News,http://www.foxnews.com/politics/2016/10/09/tru...,Trump holds pre-debate press conference with B...,16,10,9,Trump holds pre-debate press conference with...,-0.636364,-0.906496
3,133,313419,14833865,537,16-10-12,US,Fox News,http://www.foxnews.com/politics/2016/10/13/thr...,Four women claim Trump touched them inappropri...,16,10,12,Four women claim Trump touched them inapprop...,-0.055556,-0.325688
4,137,314006,14839477,1056,16-10-13,US,Fox News,http://myfox8.com/2016/10/13/2-women-accuse-tr...,2 women accuse Trump of inappropriate touching...,16,10,13,2 women accuse Trump of inappropriate touchi...,0.221053,-0.049080
5,147,314413,14846256,328,16-10-13,US,Fox News,http://nation.foxnews.com/2016/10/13/we-have-s...,'We Have Substantial Evidence of Lies': Trump ...,16,10,13,- BREAKING NEWS - Donald Trump on Thursday ...,-0.214286,-0.484418
6,153,313904,14849153,900,16-10-13,US,Fox News,http://www.foxnews.com/politics/2016/10/13/fox...,Fox News Poll: Clinton leads Trump by 7 points,16,10,13,"Related Image The poll , out Thursday , was...",0.549451,0.279318
7,179,315743,14874107,1417,16-10-15,US,Fox News,http://fox6now.com/2016/10/15/2-additional-wom...,2 additional women accuse Trump of sexual assault,16,10,15,One woman alleged that Trump slid his finger...,0.381720,0.111588
8,182,315788,14874779,674,16-10-15,US,Fox News,http://www.foxnews.com/politics/2016/10/15/tru...,Trump campaign fights back against allegation ...,16,10,15,Trump campaign fights back against allegatio...,-0.375000,-0.645132
9,187,316010,14879740,406,16-10-15,US,Fox News,http://latino.foxnews.com/latino/politics/2016...,Clinton campaign compares hacking of its e-mai...,16,10,15,Clinton campaign compares hacking of its e-m...,-0.500000,-0.770132
10,218,319283,14938231,738,16-10-19,US,Fox News,http://fox43.com/2016/10/19/debate-guests-trum...,Debate guests: Trump takes Obama's half-brothe...,16,10,19,Debate guests : Trump takes Obama 's half-br...,-0.166667,-0.436799
11,233,320072,14953275,1318,16-10-19,US,Fox News,http://www.foxnews.com/politics/2016/10/19/top...,The top 9 moments of the third presidential de...,16,10,19,The top 9 moments of the third presidential ...,-0.190476,-0.460609
12,234,320075,14953279,191,16-10-19,US,Fox News,http://www.foxnews.com/politics/2016/10/19/tru...,Trump accuses Clinton camp of falsifying gropi...,16,10,19,Trump accuses Clinton camp of falsifying gro...,-0.166667,-0.436799
13,259,322549,14996733,1137,16-10-22,US,Fox News,http://nation.foxnews.com/2016/10/23/musings-a...,"Musings Of An Average Joe: On The Economy, Hil...",16,10,22,"Musings Of An Average Joe : On The Economy ,...",0.545161,0.275029
14,260,322216,14999490,205,16-10-22,US,Fox News,http://www.foxnews.com/politics/2016/10/22/tru...,"Trump opposes AT&amp;T-Time Warner deal, says ...",16,10,22,Republican presidential nominee Donald Trump...,-0.166667,-0.436799
15,263,322338,15001253,370,16-10-22,US,Fox News,http://www.foxla.com/news/local-news/213107505...,Jessica Drake accuses Trump of sexual misconduct,16,10,22,In a press conference at attorney Gloria All...,-0.714286,-0.984418
16,288,325094,15046514,436,16-10-25,US,Fox News,http://www.mychamplainvalley.com/news/trayvon-...,Trayvon Martin unmentioned as Trump talks of b...,16,10,25,Rallying supporters in this city where 17-ye...,0.178571,-0.091561
17,305,326587,15077579,216,16-10-27,US,Fox News,http://www.foxnews.com/entertainment/2016/10/2...,Man arrested for destruction of Donald Trump's...,16,10,27,Man arrested for destruction of Donald Trump...,0.400000,0.129868
18,335,329686,15140152,793,16-10-31,US,Fox News,http://fox2now.com/2016/10/31/the-plague-of-fa...,The plague of fake news is getting worse - her...,16,10,31,The plague of fake news is getting worse -- ...,-0.181818,-0.451951

In [4]:
keywords_09 = pd.read_csv('trump_09_freq.csv')

In [8]:
list(keywords_09['media'])

['ABC News',
 'CBS News',
 'CNN',
 'Fox News',
 'Huffington Post',
 'Los Angeles Times',
 'NPR',
 'New York Post',
 'Newsweek',
 'Politico',
 'Quartz',
 'Slate Magazine',
 'TIME',
 'The Atlantic',
 'USA TODAY',
 'Washington Post']

In [13]:
list(keywords_09['neu'])

[0.3478260869565218,
 0.5,
 0.38461538461538464,
 5.551115123125783e-17,
 0.30000000000000004,
 0.475,
 0.5,
 0.0,
 0.5,
 0.48,
 0.5,
 0.2142857142857143,
 0.5,
 0.6470588235294117,
 0.09999999999999998,
 0.4901960784313726]

In [16]:
clinton = pd.read_csv('data_clinton.csv')

In [17]:
clinton

,media,polarity,normalized_polarity,tags,pos,neu,neg
0,ABC News,[ 0.03333333 -0.23809524 -0.66666667 1. ...,[-0.25755595 -0.52898452 -0.95755595 0.709110...,[-1. -1. -1. 1. 0. 1. 1. 0. 1. 0. 0. ...,0.400000,0.300000,0.300000
1,CBS News,[ 0. 0.8 0.55 0.25 ...,[-0.29088928 0.50911072 0.25911072 -0.040889...,[-1. 1. 1. 0. 1. 0. -1. -1. -1. 1. 0. ...,0.240000,0.400000,0.360000
2,CNN,[ 0.3 -0.16666667 0.34299517 0.14 ...,[ 0.00911072 -0.45755595 0.05210588 -0.150889...,[ 0. -1. 0. 0. 0. 0. 1. 1. 0. 1. -1. ...,0.190476,0.571429,0.238095
3,Fox News,[ 0.38636364 0.625 0.66666667 -0.412280...,[ 9.54743515e-02 3.34110715e-01 3.75777382e-...,[ 0. 1. 1. -1. -1. -1. 0. -1. 1. 0. 1. ...,0.400000,0.114286,0.485714
4,Huffington Post,[ 0.4 -0.53846154 -0.65277778 1. ...,[ 0.10911072 -0.82935082 -0.94366706 0.709110...,[ 0. -1. -1. 1. -1. 0. 0. 0. 1. 0. 1. ...,0.352941,0.352941,0.294118
5,Los Angeles Times,[ 0.15119363 0.58823529 0.10784314 0.440740...,[-1.39695651e-01 2.97346009e-01 -1.83046148e-...,[ 0. 1. 0. 0. -1. 1. -1. 0. 0. 0. 0. ...,0.226667,0.493333,0.280000
6,NPR,[ 0.8 -0.025 0.08333333 1. ...,[ 0.50911072 -0.31588928 -0.20755595 0.709110...,[ 1. -1. -1. 1. 0. 1. 1. -1. 1. 0. 0. 0.],0.416667,0.333333,0.250000
7,New York Post,[ 0. 0.91666667 -0.25 -0.083333...,[-0.29088928 0.62577738 -0.54088928 -0.374222...,[-1. 1. -1. -1. 1. 1. -1. 0. -1. 1. 1. -...,0.333333,0.208333,0.458333
8,Politico,[ 0.52517007 0.45454545 0.5 0.416666...,[ 0.23428078 0.16365617 0.20911072 0.125777...,[ 1. 0. 1. 0. 0. -1. 0. 0. 0. 0. 0. -...,0.298507,0.462687,0.238806
9,Quartz,[ 0.7 0. -0.03333333 0.8 ...,[ 0.40911072 -0.29088928 -0.32422262 0.509110...,[ 1. -1. -1. 1. -1. -1. 0. 1. 0. 0. 0. ...,0.187500,0.375000,0.437500
10,Reuters,[0.18181818 0.7 0.5 0.55555556 0...,[-0.1090711 0.40911072 0.20911072 0.264666...,[0. 1. 1. 1. 1.],0.800000,0.200000,0.000000
11,Slate Magazine,[-0.2 0.22857143 0.75 0.3 ...,[-0.49088928 -0.06231786 0.45911072 0.009110...,[-1. 0. 1. 0. -1. -1. 0. 0. 1. 0. -1. ...,0.105263,0.526316,0.368421
12,TIME,[1. 0.69047619 0.69318182 0.45519713 1...,[ 0.70911072 0.39958691 0.40229253 0.164307...,[ 1. 1. 1. 0. 1. 0. 1. 1. 0. -1. 0. ...,0.666667,0.266667,0.066667
13,The Atlantic,[ 0.59090909 -0.36190476 0.18730159 0.073811...,[ 0.30001981 -0.65279405 -0.1035877 -0.217077...,[ 1. -1. 0. -1. -1. 0. 1. 0. 0. 0. 0. ...,0.157895,0.578947,0.263158
14,USA TODAY,[ 0.5 0.94736842 0.625 0. ...,[ 0.20911072 0.65647914 0.33411072 -0.290889...,[ 1. 1. 1. -1. 1. 1. 1. 0. -1. 0. -1. ...,0.400000,0.314286,0.285714
15,Washington Post,[ 0.22554348 0.49957447 -0.02898551 0.466666...,[-0.06534581 0.20868518 -0.31987479 0.175777...,[ 0. 1. -1. 0. 0. 1. 1. 1. 1. 0. 0. -...,0.382812,0.500000,0.117188

In [18]:
list(clinton['media'])

['ABC News',
 'CBS News',
 'CNN',
 'Fox News',
 'Huffington Post',
 'Los Angeles Times',
 'NPR',
 'New York Post',
 'Politico',
 'Quartz',
 'Reuters',
 'Slate Magazine',
 'TIME',
 'The Atlantic',
 'USA TODAY',
 'Washington Post']

In [19]:
trump = pd.read_csv('data_trump.csv')

In [22]:
trump_clinton = trump.merge(clinton, on='media')

In [24]:
list(trump_clinton['media'])

['ABC News',
 'CBS News',
 'CNN',
 'Fox News',
 'Huffington Post',
 'Los Angeles Times',
 'NPR',
 'New York Post',
 'Politico',
 'Quartz',
 'Reuters',
 'Slate Magazine',
 'TIME',
 'The Atlantic',
 'USA TODAY',
 'Washington Post']

In [28]:
list(trump_clinton['neu_y'])

[0.3,
 0.4,
 0.5714285714285714,
 0.11428571428571427,
 0.3529411764705881,
 0.4933333333333333,
 0.3333333333333333,
 0.20833333333333345,
 0.4626865671641791,
 0.375,
 0.2,
 0.5263157894736843,
 0.2666666666666667,
 0.5789473684210527,
 0.3142857142857143,
 0.5]

In [29]:
repub = pd.read_csv('data_republic.csv')

In [33]:
trump_repub = trump.merge(repub, on='media')

In [36]:
list(trump_repub['media'])

['ABC News',
 'CBS News',
 'CNN',
 'Fox News',
 'Huffington Post',
 'Los Angeles Times',
 'NPR',
 'New York Post',
 'Politico',
 'Quartz',
 'Reuters',
 'Slate Magazine',
 'TIME',
 'The Atlantic',
 'USA TODAY',
 'Washington Post']

In [39]:
list(trump_repub['neg_y'])

[0.5384615384615384,
 0.33333333333333337,
 0.5,
 0.1428571428571429,
 0.4615384615384616,
 0.5,
 0.4166666666666667,
 0.5,
 0.4242424242424242,
 0.6,
 0.4285714285714286,
 0.2666666666666667,
 0.22222222222222227,
 0.4,
 0.4210526315789474,
 0.5090909090909091]